### ISSUE TITLE
구조체정의

### ISSUE THREAD

**Issue by greenyeast** [SoeunShin/BookAnywhere#4]

**Comment by SoeunShin** [comment]
변수 이름 정해볼까요?
- 사용자 이름
- 입실 시간
- 퇴실 시간
- 자리 번호

**Comment by SoeunShin** [comment]
> 변수 이름 정해볼까요?
> 
> * 사용자 이름
name
> * 입실 시간
start
> * 퇴실 시간
finish
> * 자리 번호
seat

어떤가요?

**Comment by greenyeast** [comment]
> > 변수 이름 정해볼까요?
> > 
> > * 사용자 이름
> >   name
> > * 입실 시간
> >   start
> > * 퇴실 시간
> >   finish
> > * 자리 번호
> >   seat
> 
> 어떤가요?

입퇴실 시간을 in out 으로 하는건 어떨까요?

**Comment by SoeunShin** [comment]
좋아요~!

**Comment by SoeunShin** [comment]
구조체 이름은 뭘로 할까요?

**Comment by SoeunShin** [comment]
User 어때요?

**Comment by greenyeast** [comment]
넵 좋아요!

**Comment by greenyeast** [comment]
`typedef struct USER{
char name[20];
int in;
int out;
int seat;
}
`

**Comment by greenyeast** [comment]
`typedef struct USER{
char name[20];
char in;
char out;
int seat;
}
`
이후에 더 편하게 수정사항 있으면 여기로 올리겠습니다!

**Comment by greenyeast** [comment]
시간 입력받을 때 형식은 char
24시간체제, 4자리로 표기, 시간 분 단위 나누는 콜론 쓰기 
ex)
> 15:05
